USE [CryptoCalculator]
GO
/****** Object:  Table [dbo].[Integration]    Script Date: 1/3/2018 1:54:10 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

if OBJECT_ID('[dbo].[Integration]') is not null
    drop table [dbo].[Integration]
GO

CREATE TABLE [dbo].[Integration](
	[ID] [uniqueidentifier] NOT NULL,
	[NAME] [nvarchar](256) NOT NULL,
	[ENDPOINT] [nvarchar](max) NOT NULL,
 CONSTRAINT [PK_Integration_ID] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[Integration] ADD  CONSTRAINT [DF_Integration_ID]  DEFAULT (newsequentialid()) FOR [ID]
GO




if OBJECT_ID('[dbo].[ef_Integration]') is not null
    drop view [dbo].[ef_Integration]
GO

create view [dbo].[ef_Integration] as
/*****************************************************************************\
    Auto-Generated By: Cosairus Database Table Generator
\*****************************************************************************/
select
    [ID],
    [NAME],
    [ENDPOINT]
from [dbo].[Integration]
GO

exec sp_addextendedproperty @name = N'autogenerated',  @value = N'', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'VIEW',  @level1name = N'ef_Integration'
GO

if OBJECT_ID('[dbo].[ef_Integration_Insert]') is not null
    drop procedure [dbo].[ef_Integration_Insert]
GO

create procedure [dbo].[ef_Integration_Insert]
    @NAME nvarchar(256),
    @ENDPOINT nvarchar(max)
as
/*****************************************************************************\
    Auto-Generated By: Cosairus Database Table Generator
\*****************************************************************************/
begin

    declare @ids table ([ID] uniqueidentifier);

    if (0 = 1)
        select [ID] from @ids;

    insert into [dbo].[Integration] (
        [NAME],
        [ENDPOINT]
    )
    output inserted.[ID] into @ids
    values (
        @NAME,
        @ENDPOINT
    );

    select [ID] from @ids;

end
GO

exec sp_addextendedproperty @name = N'autogenerated',  @value = N'', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'PROCEDURE',  @level1name = N'ef_Integration_Insert'
GO

if OBJECT_ID('[dbo].[ef_Integration_Update]') is not null
    drop procedure [dbo].[ef_Integration_Update]
GO

create procedure [dbo].[ef_Integration_Update]
    @ID uniqueidentifier,
    @NAME nvarchar(256),
    @ENDPOINT nvarchar(max)
as
/*****************************************************************************\
    Auto-Generated By: Cosairus Database Table Generator
\*****************************************************************************/
begin

    update [dbo].[Integration] set
        [NAME] = @NAME,
        [ENDPOINT] = @ENDPOINT
    where 
        ID = @ID;

end
GO

exec sp_addextendedproperty @name = N'autogenerated',  @value = N'', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'PROCEDURE',  @level1name = N'ef_Integration_Update'
GO

if OBJECT_ID('[dbo].[ef_Integration_Delete]') is not null
    drop procedure [dbo].[ef_Integration_Delete]
GO

create procedure [dbo].[ef_Integration_Delete]
    @ID uniqueidentifier
as
/*****************************************************************************\
    Auto-Generated By: Cosairus Database Table Generator
\*****************************************************************************/
begin

    delete from [dbo].[Integration]
    where 
        [ID] = @ID

end
GO

exec sp_addextendedproperty @name = N'autogenerated',  @value = N'', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'PROCEDURE',  @level1name = N'ef_Integration_Delete'
GO


