//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkCryptoCalculator
{
    using System;
    using System.Collections.Generic;
    
    public partial class Currency
    {
        public System.Guid CURRENCY_ID { get; set; }
        public string NAME { get; set; }
        public string SYMBOL { get; set; }
    }
}
