//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkCryptoCalculator
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CryptoCalculatorEntities : DbContext
    {
        public CryptoCalculatorEntities()
            : base("name=CryptoCalculatorEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Integration> Integrations { get; set; }
    
        public virtual int ef_Integration_Delete(Nullable<System.Guid> iNTEGRATION_ID)
        {
            var iNTEGRATION_IDParameter = iNTEGRATION_ID.HasValue ?
                new ObjectParameter("INTEGRATION_ID", iNTEGRATION_ID) :
                new ObjectParameter("INTEGRATION_ID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ef_Integration_Delete", iNTEGRATION_IDParameter);
        }
    
        public virtual ObjectResult<Nullable<System.Guid>> ef_Integration_Insert(byte[] nAME, string eNDPOINT)
        {
            var nAMEParameter = nAME != null ?
                new ObjectParameter("NAME", nAME) :
                new ObjectParameter("NAME", typeof(byte[]));
    
            var eNDPOINTParameter = eNDPOINT != null ?
                new ObjectParameter("ENDPOINT", eNDPOINT) :
                new ObjectParameter("ENDPOINT", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.Guid>>("ef_Integration_Insert", nAMEParameter, eNDPOINTParameter);
        }
    
        public virtual int ef_Integration_Update(Nullable<System.Guid> iNTEGRATION_ID, byte[] nAME, string eNDPOINT)
        {
            var iNTEGRATION_IDParameter = iNTEGRATION_ID.HasValue ?
                new ObjectParameter("INTEGRATION_ID", iNTEGRATION_ID) :
                new ObjectParameter("INTEGRATION_ID", typeof(System.Guid));
    
            var nAMEParameter = nAME != null ?
                new ObjectParameter("NAME", nAME) :
                new ObjectParameter("NAME", typeof(byte[]));
    
            var eNDPOINTParameter = eNDPOINT != null ?
                new ObjectParameter("ENDPOINT", eNDPOINT) :
                new ObjectParameter("ENDPOINT", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ef_Integration_Update", iNTEGRATION_IDParameter, nAMEParameter, eNDPOINTParameter);
        }
    
        public virtual int ef_Integration_Delete1(Nullable<System.Guid> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ef_Integration_Delete1", iDParameter);
        }
    
        public virtual ObjectResult<Nullable<System.Guid>> ef_Integration_Insert1(string nAME, string eNDPOINT)
        {
            var nAMEParameter = nAME != null ?
                new ObjectParameter("NAME", nAME) :
                new ObjectParameter("NAME", typeof(string));
    
            var eNDPOINTParameter = eNDPOINT != null ?
                new ObjectParameter("ENDPOINT", eNDPOINT) :
                new ObjectParameter("ENDPOINT", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.Guid>>("ef_Integration_Insert1", nAMEParameter, eNDPOINTParameter);
        }
    
        public virtual int ef_Integration_Update1(Nullable<System.Guid> iD, string nAME, string eNDPOINT)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(System.Guid));
    
            var nAMEParameter = nAME != null ?
                new ObjectParameter("NAME", nAME) :
                new ObjectParameter("NAME", typeof(string));
    
            var eNDPOINTParameter = eNDPOINT != null ?
                new ObjectParameter("ENDPOINT", eNDPOINT) :
                new ObjectParameter("ENDPOINT", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ef_Integration_Update1", iDParameter, nAMEParameter, eNDPOINTParameter);
        }
    
        public virtual int ef_Integration_Delete2(Nullable<System.Guid> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ef_Integration_Delete2", iDParameter);
        }
    
        public virtual ObjectResult<Nullable<System.Guid>> ef_Integration_Insert2(string nAME, string eNDPOINT)
        {
            var nAMEParameter = nAME != null ?
                new ObjectParameter("NAME", nAME) :
                new ObjectParameter("NAME", typeof(string));
    
            var eNDPOINTParameter = eNDPOINT != null ?
                new ObjectParameter("ENDPOINT", eNDPOINT) :
                new ObjectParameter("ENDPOINT", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.Guid>>("ef_Integration_Insert2", nAMEParameter, eNDPOINTParameter);
        }
    
        public virtual int ef_Integration_Update2(Nullable<System.Guid> iD, string nAME, string eNDPOINT)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(System.Guid));
    
            var nAMEParameter = nAME != null ?
                new ObjectParameter("NAME", nAME) :
                new ObjectParameter("NAME", typeof(string));
    
            var eNDPOINTParameter = eNDPOINT != null ?
                new ObjectParameter("ENDPOINT", eNDPOINT) :
                new ObjectParameter("ENDPOINT", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ef_Integration_Update2", iDParameter, nAMEParameter, eNDPOINTParameter);
        }
    }
}
