//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkCryptoCalculator
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public System.Guid TRANSACTION_ID { get; set; }
        public System.Guid USER_ID { get; set; }
        public System.Guid TRANSACTION_TYPE_ID { get; set; }
        public System.Guid INITIAL_CURRENCY { get; set; }
        public long INITIAL_AMOUNT { get; set; }
        public System.Guid EXCHANGED_CURRENCY { get; set; }
        public long EXCHANGED_AMOUNT { get; set; }
        public System.Guid INTEGRATION_ID { get; set; }
        public System.DateTime CREATED_ON { get; set; }
        public long FEE { get; set; }
        public System.Guid FEE_CURRENCY { get; set; }
    }
}
