//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkCryptoCalculator
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserApiConnection
    {
        public System.Guid USER_API_CONNECTION_ID { get; set; }
        public System.Guid INTEGRATION_ID { get; set; }
        public System.Guid USER_ID { get; set; }
        public string API_KEY { get; set; }
        public string API_SECRET { get; set; }
    }
}
